### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by mgolokhov** [victorwizeline/flickster#1]
I like you code structure, ApiManager, listeners with success and error callbacks.

What can be improved:

image prefix is [hardcoded](https://github.com/victorwizeline/flickster/blob/master/app/src/main/java/com/codepath/flickster/utils/Constants.java#L10);
in layout you use centerCrop (in landscape mode can see side affects) ;
Picasso does't share OkHttp instance with ApiManager;
don't use magic numbers like 5;
you cheated a bit in the Viewholder, but what if items would be 3, 4...
With multiple Viewholders can be cleaner;
Why do you use android:configChanges=”orientation|keyboardHidden|screenSize”?
Serializable is slower then Parcelable.

**Comment by victorwizeline** [comment]
I just solve some issues that you mentioned, but only the most importants issues. e.g I think that for this app Serializable vs Parcelable is not an issue

Added multiple ViewHolders .
Removed keyboardHidden.
Now the portrait/landscape layouts are correctly selected.

But thank you very much for this code review
